import argparse
import cv2
import numpy as np
import torch
import matplotlib.pyplot as plt
import os
from ultralytics import YOLO
from pytorch_grad_cam import EigenCAM
from pytorch_grad_cam.utils.image import show_cam_on_image

class YOLOXAIWrapper(torch.nn.Module):
    """A wrapper class to extract feature maps from YOLO model."""
    def __init__(self, model):
        super(YOLOXAIWrapper, self).__init__()
        self.model = model

    def forward(self, x):
        return self.model(x)

def generate_xai_heatmap(image_path, model_path, output_path, target_layer_idx):
    print("="*60)
    print("Initializing XAI Feature Extraction")
    print(f"Image: {image_path}")
    print(f"Model: {model_path}")
    print("="*60)

    # 1. Validate Image Exists
    if not os.path.exists(image_path):
        raise FileNotFoundError(f"CRITICAL ERROR: Could not find image at '{image_path}'")

    # 2. Load the trained model
    try:
        model = YOLO(model_path)
    except Exception as e:
        raise RuntimeError(f"Failed to load model '{model_path}'. Error: {e}")
    
    # Extract the exact device the model is currently running on (CPU, CUDA, or MPS)
    model_device = next(model.model.parameters()).device
    print(f"Model loaded successfully on device: {model_device}")

    # 3. Prepare the Image
    img = cv2.imread(image_path)
    img = cv2.resize(img, (640, 640)) 
    rgb_img = img[:, :, ::-1]         
    rgb_img_float = np.float32(rgb_img) / 255 
    
    # Convert image to PyTorch tensor AND move it to the correct hardware device
    tensor_img = torch.from_numpy(rgb_img_float).permute(2, 0, 1).unsqueeze(0).to(model_device)
    
    # 4. Target the specific layer for XAI extraction
    try:
        target_layers = [model.model.model[target_layer_idx]] 
        print(f"Targeting layer index [{target_layer_idx}] for EigenCAM extraction.")
    except IndexError:
        raise IndexError(f"Layer index {target_layer_idx} is out of bounds for this model architecture.")
    
    # 5. Initialize EigenCAM
    cam = EigenCAM(model=model.model, target_layers=target_layers)
    
    # 6. Generate the heatmap
    print("Generating XAI Heatmap...")
    grayscale_cam = cam(input_tensor=tensor_img)[0, :]
    cam_image = show_cam_on_image(rgb_img_float, grayscale_cam, use_rgb=True)
    
    # 7. Run standard inference to get the bounding boxes
    results = model(image_path)[0]
    annotated_frame = results.plot() 
    
    # 8. Combine the XAI heatmap with the Bounding Boxes side-by-side
    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(18, 6))
    
    ax1.imshow(rgb_img)
    ax1.set_title("Original Panoramic X-Ray")
    ax1.axis('off')
    
    ax2.imshow(cam_image)
    ax2.set_title(f"EigenCAM Activation (Layer {target_layer_idx})")
    ax2.axis('off')
    
    ax3.imshow(cv2.cvtColor(annotated_frame, cv2.COLOR_BGR2RGB))
    ax3.set_title("Disease Detections")
    ax3.axis('off')
    
    plt.tight_layout()
    plt.savefig(output_path)
    print(f"XAI analysis saved successfully to {output_path}")
    plt.show()

def parse_arguments():
    parser = argparse.ArgumentParser(description="Explainable AI (XAI) extraction for YOLO Models")
    
    # Required Arguments
    parser.add_argument("--image", type=str, required=True, help="Path to the X-ray image to analyze.")
    
    # Now defaults to the structure generated by your new train.py
    parser.add_argument("--model", type=str, default="Result/yolov8n/weights/best.pt", help="Path to your trained YOLO weights.")
    
    # Optional Arguments
    parser.add_argument("--output", type=str, default="xai_result.jpg", help="Filename to save the visualization.")
    parser.add_argument("--layer", type=int, default=9, help="Layer index to extract features from. (9 is SPPF in YOLOv8).")

    return parser.parse_args()

if __name__ == "__main__":
    args = parse_arguments()
    generate_xai_heatmap(args.image, args.model, args.output, args.layer)